### ISSUE TITLE
Peer-to-Peer review

### ISSUE THREAD

**Issue by chukwuebukaVictor** [mike2611/portfolio#4]
Your code is very semantic and responsive but there are some issues we discovered:
Each section should have a header tag() that is either from H1 to H6.
About me section is not yet completed.
The space in between your languages button will look better if it is reduced.

**Comment by chukwuebukaVictor** [comment]
Your code is very semantic and very responsive. You applied your gitflow professionally :+1: 
## :recycle: Changes Required:
- In line 347 of index.html code i think using hr to create a line will look better because the CEO will like it.
- Using downloaded font will look more professional than using a link as u did in line 19 of your index.html.
## kindly apply the changes.
Thank you.

**Comment by mike2611** [comment]
## Thank you for your recommendations, I already applied the necessary changes. :+1:
